trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'build'
    containerRegistry: '<Your_ACR_Name>'
    repository: '<Your_Repo_Name>'
    Dockerfile: '**/Dockerfile'
    tags: latest

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '<Your_Azure_Subscription>'
    appName: '<Your_App_Service_Name>'
    imageName: '<Your_ACR_Name>.azurecr.io/<Your_Repo_Name>:latest'
